title: Abacus Squid 🧮🦑
author:
  name: Thomas Pluck
description: > # this means to ignore newlines until "show_excerpts:"
  🧮🦑 | The Personal Blog of Thomas Pluck

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: pluck_thomas
    github: ThomasPluck
    linkedin: thomas-pluck

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll/scholar

# Jekyll scholar config
scholar:
  style: nature
  locale: en
  source: ./_bib
  bibliography: references.bib

# Google Analytics Tag
google_analytics: G-HE6B9ML167